### ISSUE TITLE
[FEAT] 그룹 상세 조회 API 

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#104]
## Description
본인이 속한 상세 그룹 정보 조회
groupId로 조회 가능해야 하며 형식은 다음과 같다.
```json
{
    "groupId": 1,
    "groupName": "우리 동네 모임",
    "createdAt": "2023-05-20T09:00:00Z",
    "memberCount": 5,
    "members":[
        {memberUuid1,username1},
        {memberUuid2, username2},
     ...],//이름순 or JOINAT 순
    "isAdmin": true
}
```

## Task
- [x] 상세 그룹 정보 컨트롤러 작성
- [x] 상세 그룹 정보 서비스 작성
- [x] 상세 그룹 정보 DTO 작성
- [x] Swagger 문서 업데이트
