### ISSUE TITLE
[REFACTOR] 초대 조회 수정

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#106]
## Description
초대 조회 시 이름 및 그룹 명을 반환을 같이 해줘야 한다는 요청이 들어왔다.

## Task
- [x] 초대 DTO 수정 (그룹명, 사용자 이름도 같이)
- [x] 초대 조회 서비스 REMOVED 상태는 조회안되게 처리
- [x] 초대 조회 서비스에 유저 조회하여 유저 이름도 같이 반환
- [x] 스웨거 문서 업데이트
