### ISSUE TITLE
[FEAT] Schedule  DTO, Entity에 기본값 세팅

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#23]
## Description
- DTO와 Entity에서 값을 입력받지 않더라도 기본 값을 입력될 데이터 처리
- Swagger 문서 DTO 수정으로 현재 코드와 연동이 안되어 있는 상태이다. 때문에 코드와 일치하도록 DTO 관련 Swagger 문서 업데이트

## Task
- [x] Schedule Entity categoryId 옵셔널로 설정 후 기본값 기타(categoryId = 7)로 설정
- [x] Schedule Entity title 옵셔널로 설정 후 기본값 "새로운 일정"으로 설정
- [x] CreateScheduleDto categoryId 옵셔널로 설정 후 기본값 기타(categoryId = 7)로 설정
- [x] CreateScheduleDto title 옵셔널로 설정 후 기본값 "새로운 일정"으로 설정
- [x] ScheduleResponseDto -> ResponseScheduleDto 이름 변경
- [x] ResponseScheduleDto 필드들은 모두 필수로 처리
- [x] production 환경일 때만 ssl true 설정이 되도록 수정
