### ISSUE TITLE
[FEAT] ResponseScheduleDto categoryId를 categoryName으로 반환하기

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#25]
## Description
ResponseScheduleDto categoryId를 categoryName으로 반환하기
프론트가 더 처리하기 쉽도록 변경 예정

## Task
- [ ] Schedule 엔티티에 categoryId를 외래키로 설정하고 Category 엔티티와 연결
- [ ] ResponseScheduleDto에서 categoryId 대신 categoryName을 반환하도록 수정
- [ ] ResponseScheduleDto에서 categoryName이 반환되는 부분을 Swagger 문서에 반영하고 기본값 및 필수 필드 설정이 올바른지 확인
