### ISSUE TITLE
[FEAT] 음성 기반 일정 등록 API 구현

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#29]
## Description
음성 기반 일정 등록 API 구현

## Task
- [x] GPT 모델 연결
- [x] STT 모델 연결
- [x] 관련 DTO 작성
- [x] 관련 swagger 문서 업데이트
