### ISSUE TITLE
[FIX] 음성일정등록 500error 수정

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#39]
## Description
음성 전사 서비스의 토큰 관리, 에러 처리, 그리고 재시도 메커니즘을 개선하여 서비스의 안정성, 효율성, 그리고 신뢰성을 높임.

## Task
- [ ] transcribeAudio 메서드에 토큰 자동 갱신 로직 적용
- [ ] transcribeAudio 메서드에 토큰 자동 갱신 로직 적용
- [ ] pollTranscriptionResult 메서드 각 시도마다 개별적인 에러 및 재시도 처리 구현
