### ISSUE TITLE
[FEAT] OCR을 통한 일정 추가

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#45]
## Description
이미지에서 텍스트를 추출하는 OCR(Optical Character Recognition) 기능을 추가하여 Transcription을 생성하는 새로운 기능을 구현합니다. 
이를 위해 Google Cloud Vision API를 사용할 예정입니다. 이 기능은 사용자가 이미지를 업로드하면 해당 이미지에서 텍스트를 추출하고, 이를 기반으로 일정을 생성할 수 있게 해줍니다.

## Task
- [x] Google Cloud Vision API 설정 및 연동
- [x] VoiceTranscriptionService를 확장하여 OCRTranscriptionService 생성
- [x] OCR 처리를 위한 메서드 구현 (이미지 파일 처리, API 호출, 응답 파싱)
- [x] SchedulesService에 OCR 기반 일정 생성 메서드 추가
- [x] 관련 오류 처리 및 로깅 구현
- [x] API 엔드포인트 생성 (이미지 업로드 및 OCR 처리 요청을 위한)
- [x] swagger update: API 문서 작성
