### ISSUE TITLE
[FEAT] Schedule 엔티티에 Category FK 설정 및 관련 로직 수정

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#47]
## Description
Schedule 엔티티와 Category 엔티티 간의 관계를 명확히 설정하고, 
이와 관련된 서비스 로직 및 DTO를 개선해야 한다.

## Task
- [x] Schedule 엔티티에 Category와의 ManyToOne 관계 설정
- [x] SchedulesService의 CRUD 메서드 업데이트 (create, findOne, update)
- [x] ResponseScheduleDto 최적화 (불필요한 중복 제거)
- [x] 카테고리 조회 로직 개선 (getCategoryById 메서드 구현)
- [x] 업데이트 시 카테고리 변경 로직 개선

## 예상 결과
- Schedule 조회 시 관련 Category 정보를 효율적으로 포함
- 불필요한 데이터베이스 쿼리 감소
- API 응답 데이터 구조 개선
- 카테고리 관련 오류 처리 강화
