### ISSUE TITLE
[FEAT] Auth 및 User 관련 작업

### ISSUE THREAD

**Issue by nullisdefined** [nullisdefined/nanalmoa-BE#51]
## Description
Auth 및 User 관련 작업입니다. 

## Task
- [x] User 엔티티 userUuid 포함하게 수정
- [x] User 모듈에서 사용자 정보 조회 API 구현
- [x] OAuth에서 userId를 userUuid 사용하는 것으로 로직 변경
