### ISSUE TITLE
[FEAT] 일반 회원가입 구현

### ISSUE THREAD

**Issue by nullisdefined** [nullisdefined/nanalmoa-BE#56]
## Description
전화번호로 일반 회원가입 API 구현 입니다.

## Task
- [x] 전화번호 인증 가능한 오픈 API 탐색
- [x] 백엔드 전화번호 인증 API 구현
- [x] 전화번호 인증 테스팅
- [x] 일반 회원가입 API
- [x] 일반 로그인 API
- [x] 리프레시 로직에 일반 JWT 토큰 추가
- [x] User 엔티티 수정 (phone_number 칼럼 추가)
- [x] 소셜 로그인 res dto에 phone_number 추가
- [x] 사용자 정보 조회 로직에 일반 추가
