### ISSUE TITLE
[FEAT] 그룹 관련 엔티티 생성

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#73]
## Description
그룹 관련 엔티티 생성
특히 매니투매니 관계를 생각해서 엔티티를 생성할 예정이다.

## Task
- [x] group 엔티티 생성
- [x] user_group 엔티티 생성
- [x] group_schedule 엔티티 생성
