### ISSUE TITLE
[REFACTOR] 관리자, 일정 auth 적용 및 관련 리팩토링

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#80]
## Description
프론트측에서 userId 대신 userUuid의 반환을 요구했음. 사유는 다음과 같다. 
- UUID는 고유한 랜덤 문자열로 구성되어 있어 추측이 어렵고, 특정 패턴이 없어 보안적으로 안전하다.
- userId가 노출되면 공격자는 해당 값의 증가 패턴을 통해 데이터베이스 구조나 다른 사용자에 대한 정보를 추론할 수 있다. 하지만 UUID를 사용하면 이러한 데이터 탐색이 어려워진다.

또한 Auth가 완성되어 다음과 같은 기능들을 추가 및 변경해야 한다.

## Task
- [x] 일정관련 api들 jwt 가드 사용하도록 변경
- [x] 일정 엔티티에 createdAt과 updatedAt 추가
- [x] 기존 userId들을 다 userUuid의 사용으로 변경
- [x] 헤더를 통해서 토큰 받고 해당 토큰으로 로그인 검사 후 유저 정보 받기
- [x] 종일옵션 선택 시 시작 시간과 종료 시간 검증 후 변환
- [x] 관리자 초대 시 실제 유저 테이블에 있는 정보를 바탕으로 초대가 갈 수 있도록 검증 추가
- [x] 관리자 초대 status CANCLE 추가
- [x] 관리자 초대 관련 오류는 메세지를 통해서 프론트 측에 전달
- [x] 관련 스웨거 업데이트
