### ISSUE TITLE
[FEAT] OCR 등록 API 

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#83]
## Description
CLOVA OCR 기능 구현 
## Task
- [x] 클로바 api 연동
- [x] 기존 클로바 코드를 구글 스토리지 -> url 변환 -> 클로바 전달 에서 바로 사진을 클로바에게 전달하도록 수정
- [x] OCR 결과를 OCR 데이터로 튜닝된 GPT 모델에 삽입
- [x] GPT 모델 결과를 JSON 형식으로 파싱
