### ISSUE TITLE
[FEAT] Group 관련 DTO 작성

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#86]
## Description
생성된 Group Entity에 맞게 Group 관련 DTO 작성 해야한다.
뿐만 아니라 변경된 Schedule Entity에 맞게 시딩 파일 수정과 dataSource파일 수정이 이루어져야 한다.

## Task
- [x] 시딩 파일에서 isGroupSchedule 삭제
- [x] group create dto
- [x] group member invitation dto 
- [x] group invitation response dto
- [x] group remove dto
- [x] group member remove dto
- [x] group response dto 
- [x] group memeber response dto
