### ISSUE TITLE
[TEST] 일정 수동 등록 관련 단위 테스트

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#9]
## Description
일정 수동 등록 관련 단위 테스트 코드 작성
## Task
- [x] 새 일정 생성 테스트
- [x] 일정 업데이트 테스트
- [x] 일정 삭제 테스트
- [x] 일정 조회 테스트
- [x] 특정 월의 일정 조회 테스트
- [x] 주 단위 일정 조회 테스트
- [x] 특정 날짜 범위 일정 조회 테스트
- [x] 사용자의 모든 일정 조회 테스트
