### ISSUE TITLE
[FEAT] user routine table 생성

### ISSUE THREAD

**Issue by Baguette-bbang** [nullisdefined/nanalmoa-BE#94]
## Description
유저의 하루 루틴에 대해서 조사를 받고 저장하는 테이블이다.
해당 시간대를 이용하여 유저의 패턴을 파악하고 
복약일정을 설정하기 위함이다.

추가적으로 모든 엔티티의 실제 테이블명을 @Entity안에 명시 하였고
스네이크 케이스를 사용하도록 설정하였다.

## Task
- [x] 모든 엔티티의 실제 테이블명을 @Entity안에 명시 및 스네이크 사용 설정
- [x] 유저 루틴엔티티 생성
  - [x] 기상시간
  - [x] 아침식사 시간
  - [x] 점심식사 시간
  - [x] 저녁식사 시간
  - [x] 취침시간
  - [x] 유저 uuid FK 설정
